### ISSUE TITLE
The plugin does not support the "." character in package names

### ISSUE THREAD

**Issue by bibimorlet** [meanmail/requirements#11]
The plugin does not support the "." character in package names and expects CRLF, LSBRACE or  RELATION character (see screenshot)
![image](https://user-images.githubusercontent.com/15572717/69067344-32c31400-0a23-11ea-8614-800088646f87.png)

**Comment by meanmail** [comment]
What version of the plugin do you have installed?

**Comment by bibimorlet** [comment]
version: v2019.4

**Comment by meanmail** [comment]
The full syntax was implemented in 2019.5. You can update the plugin to fix this error

**Comment by bibimorlet** [comment]
I see all the plugin versions on https://plugins.jetbrains.com/plugin/10837-requirements/
but the version after 2019.4 (e.g 2019.6) are not compatible with "Pycharm 2019.1.4 (Professional Edition)"
(see screenshot)
![image](https://user-images.githubusercontent.com/15572717/69165213-83a13e00-0af1-11ea-81db-0b824eafc5fd.png)

My IDE suggests me to revert it to the version 2019.4.
![image](https://user-images.githubusercontent.com/15572717/69165234-8dc33c80-0af1-11ea-9c5f-844ec3d0cab0.png)

**Comment by meanmail** [comment]
I have built version 2019.6.0.1 for Intellij 2019.1-2019.1.4. It can be downloaded after about two business days.

**Comment by meanmail** [comment]
@bibimorlet plugin can be downloaded! I will be grateful if you confirm that the plugin has earned
