### ISSUE TITLE
First line --options should not me marked as errors

### ISSUE THREAD

**Issue by wimglenn** [meanmail/requirements#12]
It's pretty common to put some options on first line such as custom --index-url  
These are not errors should not be indicated as errors
See the [Requirements file format](https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format) docs.

**Comment by samupl** [comment]
![Zrzut ekranu z 2019-12-19 11-02-01](https://user-images.githubusercontent.com/536208/71164321-18ad6900-224f-11ea-869c-72603c01fb58.png)

Confirmed to still exist in `2019.6.3-193`

**Comment by meanmail** [comment]
2019.7 Released. In two days, the version will be available for download [Change-notes](https://meanmail.dev/post/3)

**Comment by meanmail** [comment]
2019.7 available for download
