### ISSUE TITLE
-e does not accept local directories

### ISSUE THREAD

**Issue by robert-schmidtke** [meanmail/requirements#13]
**Description of the bug**
When using a local path for an editable requirement (`-e ./submodule`) in `requirements.txt`, the inspection returns `File is not exists` (I'd go with `File does not exist`), with a detailed description that `./submodule is a directory`. `pip install -e` expects either a VCS URL or a path to a local project, where a `setup.py` can be located.

**Steps to reproduce**
Clone any Python project with a `setup.py` file, use it as an editable requirement via `-e` in `requirements.txt` and then run the PyCharm code inspection with this plugin installed.

**Expected behavior**
`./submodule is a directory` should not be reported as an error.

**IDE**
 - OS: Ubuntu 18.04.3 LTS (Linux 4.15.0-1064-oem)
 - Product: PyCharm 2019.2.5 (Community Edition)
 - Version: Build #PC-192.7142.56, built on November 19, 2019
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o (11.0.4+10-b304.77 amd64)

**Plugin**
 - Version: 2019.6

**Comment by meanmail** [comment]
In two days, the fixed version will be available for download. Need to wait for confirmation from Jetbrains

**Comment by meanmail** [comment]
Release 2019.6.1 allowed to download!
[About release](https://meanmail.dev/post/2)
