### ISSUE TITLE
Incompatible with PyCharm 2019.3 (Requirement=2019.6.0.1)

### ISSUE THREAD

**Issue by allburov** [meanmail/requirements#14]
**Describe the bug**
After I've update PyCharm to 2019.3, it says: `Plugin Error: Plugin "Requirements" is incompatible (target build range is 192.5728 to 192.*).`

**To Reproduce**
1. Update PyCharm to 2019.3
2. Restart
3. See error

**Expected behavior**
Plugin works

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: Ubuntu 18.04.3 LTS
 - Product: PyCharm Professional Edition
 - Version 2019.3 , 28 November, 2019 (It's hard to type full version, because pycharm just show popup without ability to copy-paste)
 - JRE Version: 11.0.4 OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2019.6

**Additional context**
Your plugin is very useful!

**Comment by deeppunster** [comment]
Same message occurs on a Mac (OS: 10.14.6)
Pycharm Info:
PyCharm 2019.3 (Professional Edition)
Build #PY-193.5233.109, built on November 28, 2019
...
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
(Able to get a copy of the text in the About dialog box by clicking on the clipboard icon to the left of the text (Mac only feature?)).

**Comment by meanmail** [comment]
Today or tomorrow, a version compatible with 2019.3 will be available for download. Need to wait for confirmation from Jetbrains

**Comment by h0rn3t** [comment]
thanks

**Comment by h0rn3t** [comment]
Спасибо очень крутой плагин, я думаю станет очень популярным, не бросайте)

**Comment by meanmail** [comment]
A version compatible with 2019.3 can be downloaded
