### ISSUE TITLE
Spaces not recognized

### ISSUE THREAD

**Issue by flying-sheep** [meanmail/requirements#19]
My valid requirements.txt contains `sphinx ~= 2.0`. I have Sphinx 2.2 installed.

I see an error: “RequirementsTokenType.VERSION expected” at the space position.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/291575/71771027-204e5c80-2f35-11ea-8940-10269b7a411e.png)

**IDE**
 - OS: Arch Linux
 - Product: PyCharm Professional Edition
 - Version: 2019.3.1
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Plugin**
 - Version 2019.7-193

**Comment by meanmail** [comment]
[Released](https://meanmail.dev/post/4)
