### ISSUE TITLE
false positive on double specification

### ISSUE THREAD

**Issue by fmigneault** [meanmail/requirements#20]
**Describe the bug**
When having a conditional specification, the double-entry generates a false positive "duplicate" because it indeed refers to the same package. Because the version applied to each package entry depends on a following condition, they need to be entered twice.

**To Reproduce**
Add any specification in the following form: 
```
pkg>=1.x,<2; python_version < "3"
pkg>=2; python_version >= "3"
```

**Expected behavior**
Duplicate requirement should not be flagged as it represents two valid distinct conditions.

**IDE (please complete the following information. See Main Menu -> Help -> About):**
 - OS: ubuntu 16.04
 - Product: PyCharm Community
 - Version 193.6015.41
 - JRE Version: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2019.7-193

**Additional context**

**Comment by meanmail** [comment]
Thanks. Environmental markers will be supported in 2020.1

**Comment by meanmail** [comment]
Plugin Requirements 2020.1 is [Released](https://meanmail.dev/post/5)!
