### ISSUE TITLE
sys_platform marker not working

### ISSUE THREAD

**Issue by SimonIT** [meanmail/requirements#21]
**Describe the bug**
The plugin suggests to install a dependency marked as linux platform only on windows

**Screenshots**
![image](https://user-images.githubusercontent.com/11720038/73122846-aafd0700-3f89-11ea-86bf-dd0eb22079b2.png)

**IDE (please complete the following information. See Main Menu -> Help -> About):**
PyCharm 2019.3.2 (Professional Edition)
Build #PY-193.6015.41, built on January 21, 2020
Runtime version: 11.0.5+10-b520.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1975M
Cores: 8
Registry: 
Non-Bundled Plugins: BashSupport, CMD Support, com.alayouni.ansiHighlight, com.intellij.ideolog, mobi.hsz.idea.gitignore, org.toml.lang, ru.meanmail.plugin.requirements

**Plugin (please complete the following information. See Main Menu -> File -> Settings -> Plugins):**
 - Version 2019.7-193

**Comment by meanmail** [comment]
Thanks. Environment markers will be supported in 2020.1

**Comment by meanmail** [comment]
Plugin Requirements 2020.1 is [Released](https://meanmail.dev/post/5)!

**Comment by masklinn** [comment]
@meanmail how is the support supposed to work? I've got a project with a bunch of `sys_platform` markers and all the deps are marked as "unused" whether the `sys_platform` matches the current environment or not.

**Comment by masklinn** [comment]
@meanmail how is the support supposed to work? I've got a project with a bunch of `sys_platform` markers and all the deps are marked as "unused" whether the `sys_platform` matches the current environment or not.

**Comment by masklinn** [comment]
@meanmail how is the support supposed to work? I've got a project with a bunch of `sys_platform` markers and all the deps are marked as "unused" whether the `sys_platform` matches the current environment or not.
