### ISSUE TITLE
Error on Parsing Packages with a '.' in their name

### ISSUE THREAD

**Issue by Baneeishaque** [meanmail/requirements#3]
![Capture](https://user-images.githubusercontent.com/6133009/63448457-9311dc00-c45b-11e9-81fb-6d73b68fd85c.PNG)

**Comment by meanmail** [comment]
@Baneeishaque thanks for the feedback. I will fix it in the near future

**Comment by justalemon** [comment]
Hi, is there any planned fix for this? I'm getting this problem with [discord.py](https://pypi.org/project/discord.py/):

![image](https://user-images.githubusercontent.com/11861253/66398945-0e503280-e9b5-11e9-8194-9c4113d0806d.png)

**Comment by meanmail** [comment]
2019.5 released!
It supports almost the entire syntax of requirements.txt. The plugin will be available after verification by JetBrains. It will take about 2 business days
