### ISSUE TITLE
Error parsing requirements with extras separated by comma

### ISSUE THREAD

**Issue by piraz** [meanmail/requirements#4]
When I add a requirement with extras separated by comma an error is displayed to the line with this message:

> RequirementsTokenType.RSBRACE expected, got ','

Steps to reproduce:

1. Create a requirements.txt
1. Add the line:
```firenado[redis, sqlalchemy]==0.1.7.6```
1. Observe the message

**Comment by meanmail** [comment]
@piraz thanks for the feedback. I will fix it in the near future

**Comment by meanmail** [comment]
2019.5 released!
It supports almost the entire syntax of requirements.txt. The plugin will be available after verification by JetBrains. It will take about 2 business days
