### ISSUE TITLE
Separating version specifiers by a comma causes an error to appear

### ISSUE THREAD

**Issue by davidginzbourg** [meanmail/requirements#5]
![image](https://user-images.githubusercontent.com/3932179/64218961-7cff1500-ce78-11e9-8774-0e489d23e6e5.png)
> RequirementsTokenType.CRLF or RequirementsTokenType.LSBRACE expected, got ','.

Using `v2019.4`.

**Comment by meanmail** [comment]
@davidginzbourg thanks for the feedback. I will fix it in the near future (2019.5)

**Comment by rolep** [comment]
Similar while specifying extra - RequirementsTokenType.CRLF expected, got '='.
First occurrence marked as invalid and all later lines are not processed.

package[extra]==1.1.1

PyCharm 2019.2.3

**Comment by Chaffelson** [comment]
Similarly flags package names like 'ruamel.yaml' as invalid.

**Comment by meanmail** [comment]
2019.5 released!
It supports almost the entire syntax of requirements.txt. The plugin will be available after verification by JetBrains. It will take about 2 business days
