### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by ilovetogetspamed** [meanmail/requirements#9]
Your plugin description needs to be updated unless you meant to use 'Right' and not 'Write' in the your description:
```
 Right Python requirements.txt Python package Manager! More info GitHub Please give me feedback
```
'Right' means true or correct as a fact.

You probably want to use 'create' or 'write' instead of 'right'.

**Comment by meanmail** [comment]
Thanks. Description will be corrected.

**Comment by meanmail** [comment]
In two days, the fixed version will be available for download. Need to wait for confirmation from Jetbrains

**Comment by meanmail** [comment]
Release 2019.6.1 allowed to download!
[About release](https://meanmail.dev/post/2)
